#!/usr/bin/env python3
# ============================================================
# embed_driver.py — 将漏洞驱动 .sys 文件转换为 C++ 嵌入字节数组
#
# 用法: python embed_driver.py RTCore64.sys
# 输出: rtcore64_embed.h (直接放在 stealth_lib 目录下)
#
# 支持驱动: RTCore64.sys, gdrv.sys 等
# ============================================================

import sys
import os

def embed_driver(sys_path):
    if not os.path.exists(sys_path):
        print(f"[ERROR] 文件不存在: {sys_path}")
        return False

    basename = os.path.basename(sys_path)
    name_no_ext = os.path.splitext(basename)[0]
    output_name = f"{name_no_ext.lower()}_embed.h"

    with open(sys_path, 'rb') as f:
        data = f.read()

    size = len(data)
    print(f"[INFO] 读取 {basename}: {size} bytes ({size/1024:.1f} KB)")

    # 生成 C 头文件
    lines = []
    lines.append(f"// Auto-generated by embed_driver.py")
    lines.append(f"// Source: {basename} ({size} bytes)")
    lines.append(f"#pragma once")
    lines.append(f"#include <cstdint>")
    lines.append(f"")
    lines.append(f"namespace stealth {{ namespace embedded {{")
    lines.append(f"")
    lines.append(f"// {basename} 嵌入字节数组 ({size} bytes)")
    lines.append(f"static const uint8_t {name_no_ext}_data[] = {{")

    # 每行 16 字节
    for i in range(0, size, 16):
        chunk = data[i:i+16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        if i + 16 < size:
            lines.append(f"    {hex_str},")
        else:
            lines.append(f"    {hex_str}")

    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"static constexpr size_t {name_no_ext}_size = {size};")
    lines.append(f"")
    lines.append(f"}}}} // namespace stealth::embedded")

    # 写入输出文件 (放到脚本同目录, 用户手动复制到 stealth_lib)
    output_dir = os.path.dirname(os.path.abspath(__file__))
    output_path = os.path.join(output_dir, output_name)

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"[OK] 生成: {output_path}")
    print(f"      复制到 stealth_lib/{output_name} 后重新编译即可")
    return True

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("用法: python embed_driver.py <driver.sys>")
        print("示例: python embed_driver.py RTCore64.sys")
        sys.exit(1)

    embed_driver(sys.argv[1])
